server:
  port: 8080
  servlet:
    context-path: /bookmanager
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    name: source
    url: jdbc:mysql://localhost:3306/db_book_manager?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1201
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern : /**
  jmx:
    enabled: false

  thymeleaf:
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /bookManager # rabbitmq的虚拟host
    username: whg # rabbitmq的用户名
    password: 1201 # rabbitmq的密码
    publisher-confirms: true #如果对异步消息需要回调必须设置为true


mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
    - classpath*:cn/hnist/bookmanager/mapper/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  row-bounds-with-count: true


logging:
  config: classpath:log4j2.yml

