server:
  port: 8080
  servlet:
    context-path: /bookmanager
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    name: source
    url: jdbc:mysql://localhost:3306/db_bookmanager?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: zxw
    password: 123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern : /**
  jmx:
    enabled: false

  thymeleaf:
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html



mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
    - classpath*:cn/hnist/bookmanager/mapper/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  row-bounds-with-count: true


logging:
  config: classpath:log4j2.yml

